name: issue-text

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "Hey, thank you for creating an issue. We will normally respond within 24 hours."
        GITHUB_TOKEN: ${{ secrets.BOT }}
        
    - uses: stefanbuck/github-issue-parser@v2
      id: issue-parser
      with:
        template-path: .github/ISSUE_TEMPLATE/bug_report.yml
        
    - run: echo '${{ steps.issue-parser.outputs.jsonString }}'
    
    - run: echo ${{ steps.issue-parser.outputs.issueparser_what_browser_are_you_seeing_the_problem_on }}
    
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: ${{ steps.issue-parser.outputs.issueparser_what_browser_are_you_seeing_the_problem_on }}
        github_token: ${{ secrets.BOT }}
        
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "new-json-file.json"
        json: '{"name": "Super Smash Aeugh Web", "icon": "https://cdn.discordapp.com/attachments/880568849085374504/945988898406953000/pufferfish.png", "type": "app", "data": {"type": "IFrame", "url": "url-here", "gallery": [ "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQoPckz603CcUVyrUwDAX04l7OXMpKZQXI4QUr9P5_UMas37EMmrSUNn9JgK5Yzz0R8Kw&usqp=CAU", "https://www.researchgate.net/profile/Robert-Morris-5/publication/228389474/figure/fig2/AS:393642368880642@1470863062228/A-screenshot-of-the-Scratch-programming-blocks.png", "https://techcrunch.com/wp-content/uploads/2019/01/ProjectEditor.png?w=430&h=230&crop=1" ], "desc": "Scratch is a high-level block-based visual programming language and website targeted primarily at children 8–16 as an educational tool for programming. ", "feat": "Users on the site, called Scratchers, can create projects on the website using a block-like interface." }, "url": "https://melonicoverlord.github.io/aeughweb/", "Type": "game"}'
        
    - name: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.BOT }}
        commit-message: Add ${{ steps.issue-parser.outputs.issueparser_what_browser_are_you_seeing_the_problem_on }}
        title: Add ${{ steps.issue-parser.outputs.issueparser_what_browser_are_you_seeing_the_problem_on }}
        body: Add ${{ steps.issue-parser.outputs.issueparser_what_browser_are_you_seeing_the_problem_on }}    
