name: issue-text

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "Hey, thank you for creating an issue. We will normally respond within 24 hours."
        GITHUB_TOKEN: ${{ secrets.BOT }}
        
    - uses: stefanbuck/github-issue-parser@v2
      id: issue-parser
      with:
        template-path: .github/ISSUE_TEMPLATE/bug_report.yml
        
    - run: echo '${{ steps.issue-parser.outputs.jsonString }}'
    
    - run: echo ${{ steps.issue-parser.outputs.issueparser_what_browser_are_you_seeing_the_problem_on }}
    
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: ${{ steps.issue-parser.outputs.issueparser_what_browser_are_you_seeing_the_problem_on }}
        github_token: ${{ secrets.BOT }}
        
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "new-json-file.json"
        json: ${{ secrets.MY_JSON }}
          
    - name: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.BOT }}
        commit-message: Add ${{ steps.issue-parser.outputs.issueparser_what_browser_are_you_seeing_the_problem_on }}
        title: Add ${{ steps.issue-parser.outputs.issueparser_what_browser_are_you_seeing_the_problem_on }}
        body: Add ${{ steps.issue-parser.outputs.issueparser_what_browser_are_you_seeing_the_problem_on }}    
